# Generated by Django 5.1.4 on 2026-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile_old_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зеленый'), ('yellow', 'Желтый'), ('white', 'Белый'), ('black', 'Черный'), ('pink', 'Розовый'), ('purple', 'Фиолетовый'), ('orange', 'Оранжевый'), ('brown', 'Коричневый'), ('gold', 'Золотой'), ('silver', 'Серебряный'), ('multi', 'Многоцветный')], max_length=20, null=True, verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.tag', verbose_name='Теги'),
        ),
    ]
