# Generated by Django 5.1.4 on 2026-01-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_tagcategory_alter_tag_options_tag_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category__order', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tagcategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию тега', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='store.tagcategory', verbose_name='Категория тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Например: сабантуй, красный, бархат, серьги', max_length=50, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(choices=[('fabric', 'Ткани'), ('color', 'Цвет'), ('event', 'Событие'), ('product', 'Изделие'), ('style', 'Стиль'), ('ornament', 'Орнамент')], max_length=50, unique=True, verbose_name='Название категории'),
        ),
    ]
