# Generated by Django 5.1.4 on 2026-01-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_tag_options_remove_tag_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_active',
        ),
    ]
