# Generated by Django 5.1.4 on 2026-02-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_tag_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='articles/gallery/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник изображения')),
            ],
            options={
                'verbose_name': 'Изображение статьи',
                'verbose_name_plural': 'Изображения статей',
            },
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(choices=[('fabric', 'Материал'), ('color', 'Цвет'), ('event', 'Событие'), ('product', 'Изделие'), ('style', 'Стиль'), ('ornament', 'Орнамент')], max_length=50, unique=True, verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('article_type', models.CharField(choices=[('costume', 'Татарский костюм'), ('headwear', 'Головные уборы'), ('jewelry', 'Украшения'), ('ornament', 'Орнаменты и узоры'), ('craft', 'Ремесла и техники'), ('holiday', 'Праздники и традиции'), ('material', 'Материалы и ткани'), ('modern', 'Современное прочтение')], max_length=50, verbose_name='Тип статьи')),
                ('short_description', models.TextField(help_text='Отображается в карточке статьи', verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('main_image', models.ImageField(upload_to='articles/main/', verbose_name='Главное изображение')),
                ('author', models.CharField(default='Администратор сайта', max_length=100, verbose_name='Автор')),
                ('source', models.CharField(blank=True, help_text='Например: "Декоративно-прикладное искусство казанских татар"', max_length=200, verbose_name='Источник')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery_images', models.ManyToManyField(blank=True, to='store.articleimage', verbose_name='Галерея изображений')),
                ('related_products', models.ManyToManyField(blank=True, help_text='Товары, которые иллюстрируют статью', to='store.product', verbose_name='Связанные товары')),
                ('related_tags', models.ManyToManyField(blank=True, help_text='Теги, связанные с темой статьи', to='store.tag', verbose_name='Связанные теги')),
            ],
            options={
                'verbose_name': 'Историческая статья',
                'verbose_name_plural': 'Исторические статьи',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductHistoricalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_fact', models.CharField(help_text='Например: "Традиционный головной убор замужних женщин"', max_length=200, verbose_name='Краткий исторический факт')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('fact_type', models.CharField(choices=[('origin', 'Происхождение'), ('meaning', 'Значение'), ('tradition', 'Традиция использования'), ('symbol', 'Символизм'), ('modern', 'Современное прочтение')], default='tradition', max_length=50, verbose_name='Тип факта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_facts', to='store.product')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_links', to='store.historicalarticle', verbose_name='Связанная статья')),
            ],
            options={
                'verbose_name': 'Историческая связь товара',
                'verbose_name_plural': 'Исторические связи товаров',
            },
        ),
    ]
