# Generated by Django 5.1.4 on 2026-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_articleimage_alter_tagcategory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarticle',
            name='gallery_images',
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Товары, связанные с темой статьи', to='store.product', verbose_name='Связанные товары'),
        ),
    ]
