# Generated by Django 5.1.4 on 2026-02-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_historicalarticle_gallery_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='related_tags',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='source',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='views',
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='article_type',
            field=models.CharField(choices=[('costume', 'Татарский костюм'), ('headwear', 'Головные уборы'), ('jewelry', 'Украшения'), ('ornament', 'Орнаменты и узоры'), ('craft', 'Ремесла и техники'), ('holiday', 'Праздники и традиции')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='main_image',
            field=models.ImageField(upload_to='articles/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='store.product', verbose_name='Связанные товары'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.DeleteModel(
            name='ProductHistoricalLink',
        ),
    ]
