# Generated by Django 5.1.4 on 2026-02-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_delete_articleimage_remove_historicalarticle_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalarticle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Историческая статья', 'verbose_name_plural': 'Исторические статьи'},
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='order',
        ),
    ]
