# Generated by Django 5.1.4 on 2026-02-28 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_historicalarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name': 'Категория тегов', 'verbose_name_plural': 'Категории тегов'},
        ),
        migrations.RemoveField(
            model_name='tagcategory',
            name='order',
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
