# Generated by Django 5.1.4 on 2026-04-21 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_tag_options_alter_tagcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('response', models.TextField(verbose_name='Ответ стилиста')),
                ('products_data', models.JSONField(blank=True, default=list, verbose_name='Предложенные товары')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История чата',
                'verbose_name_plural': 'Истории чатов',
                'ordering': ['-created_at'],
            },
        ),
    ]
