# Generated by Django 5.1.4 on 2026-02-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_email_error_order_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
